[package]
name = "brannon"
version = "0.1.0"
edition = "2024"

[dependencies]
time = { version = "0.3.43", features = ["formatting", "local-offset"] }
libc = "0.2.175"
trpl = "0.3.0"

[lints.clippy]
new_without_default = "allow"
